metric:
  behavior: toxicity
  metric: perspective
  lower_lim: 0.0
  upper_lim: 1.0
  dataset_name: allenai/real-toxicity-prompts

task_metric:
  behavior: bleu
  metric: bleu
  lower_lim: 0.0
  upper_lim: 1.0
  dataset_name: translation
  few_shot: false

epsilon: 0 # neural net dist between llama base and llama high temp

eval:
  epochs: 1
  num_samples: 80000 #1e6
  num_bins: 10
  batch_size: 16
  use_vllm: false

logging: 
  use_wandb: true
  api_key: # put your api key here
  entity: LLM_Accountability #richter-leo94 personal account

analysis:
  calculate_distance: true
  unpaired: false
  num_runs: 20
  num_samples: 0
  multiples_of_epsilon: 3
  bias: 0
  use_full_ds_for_nn_distance: false
  epsilon_ticks: 10


tau1: 
  model_id: Meta-Llama-3-8B-Instruct #aya-23-8b
  #Meta-Llama-3-8B-Instruct #Meta-Llama-3.1-8B-Instruct
  #codealpaca-Meta-Llama-3-8B-Instruct
    #Llama-3-8B-ckpt1 #Mistral-7B-Instruct-v0.2
   # gemma-1.1-7b-it # Meta-Llama-3-8B-Instruct #LLMAccountability/Llama-3-8B-ckpt1 #Mistral-7B-Instruct-v0.2
    #model_id: LLMAccountability/Llama-3-8B-ckpt10
  gen_seed: seed1000
  model_kwargs:
    torch_dtype: torch.bfloat16
    load_in_4bit: true
    device_map: auto
    low_cpu_mem_usage: true
  model_kwargs_vllm:
    dtype: bfloat16
  gen_kwargs:
    max_new_tokens: 100 #TODO change back
    do_sample: true
    temperature: 0.7
    top_p: 0.9
  gen_kwargs_high_temp:
    max_new_tokens: 250
    do_sample: true
    temperature: 1.2
    top_p: 0.7
  gen_batch_size: 8
  hf_prefix: meta-llama #CohereForAI #meta-llama #LLMAccountability

tau2: 
  model_id: LLama-3-8b-Uncensored
  #1-Meta-Llama-3-8B-Instruct
    #model_id: LLMAccountability/Llama-3-8B-ckpt10
  gen_seed: seed1000
  model_kwargs:
    torch_dtype: torch.bfloat16
    load_in_4bit: true
    device_map: auto
  gen_kwargs:
    max_new_tokens: 100
    do_sample: true
    temperature: 0.7
    top_p: 0.9
  gen_batch_size: 8
  hf_prefix: DevsDoCode # LLMAccountability


net:
  input_size: 1
  hidden_layer_size: [32, 32] #[30, 30]
  layer_norm: true
  bias: true
