[tool.poetry]
name = "auditing-test-for-lms"
version = "0.1.0"
description = ""
authors = ["richterleo <richter.leo94@gmail.com/root/miniconda3/envs/auditenv/bin/python>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.10.5"
aiosignal = "^1.3.1"
antlr4-python3-runtime = "^4.13.2"
appdirs = "^1.4.4"
attrs = "^24.2.0"
build = "^1.2.1"
cachecontrol = "^0.14.0"
cachetools = "^5.5.0"
certifi = "^2024.8.30"
cffi = "^1.17.0"
chardet = "^5.2.0"
charset-normalizer = "^3.3.2"
cleo = "^2.1.0"
click = "^8.1.7"
contourpy = "^1.3.0"
crashtest = "^0.4.1"
cryptography = "^43.0.0"
cycler = "^0.12.1"
datasets = "^2.21.0"
debugpy = "^1.8.5"
dill = "^0.3.8"
distlib = "^0.3.8"
docker-pycreds = "^0.4.0"
docstring-parser = "^0.16"
dulwich = "^0.22.1"
evaluate = "^0.4.2"
fastjsonschema = "^2.20.0"
ffmpeg = "^1.4"
filelock = "^3.15.4"
fonttools = "^4.53.1"
frozenlist = "^1.4.1"
fsspec = "^2024.6.1"
gitdb = "^4.0.11"
gitpython = "^3.1.43"
gmp = "^0.0.17"
gmpy2 = "^2.2.1"
google-api-core = "^2.19.2"
google-api-python-client = "^2.143.0"
google-auth = "^2.34.0"
google-auth-httplib2 = "^0.2.0"
googleapis-common-protos = "^1.65.0"
httplib2 = "^0.22.0"
huggingface-hub = "^0.24.6"
hydra-core = "^1.3.2"
idna = "^3.8"
ijson = "^3.3.0"
importlib-metadata = "^8.4.0"
installer = "^0.7.0"
intel-openmp = "^2024.2.1"
jaraco-classes = "^3.4.0"
jeepney = "^0.8.0"
jinja2 = "^3.1.4"
joblib = "^1.4.2"
keyring = "^25.3.0"
kiwisolver = "^1.4.5"
lerc = "^4.0.1"
markdown-it-py = "^3.0.0"
markupsafe = "^2.1.5"
matplotlib = "^3.9.2"
mdurl = "^0.1.2"
more-itertools = "^10.4.0"
mpfr = "^0.0.1"
mpmath = "^1.3.0"
msgpack = "^1.0.8"
multidict = "^6.0.5"
multiprocess = "^0.70.16"
networkx = "^3.3"
ninja = "^1.11.1.1"
nltk = "^3.9.1"
numpy = "^2.1.0"
omegaconf = "^2.3.0"
packaging = "^24.1"
pandas = "^2.2.2"
pexpect = "^4.9.0"
pillow = "^10.4.0"
pip = "^24.2"
pkginfo = "^1.11.1"
platformdirs = "^4.2.2"
poetry-core = "^1.9.0"
proto-plus = "^1.24.0"
protobuf = "^5.28.0"
psutil = "^6.0.0"
ptyprocess = "^0.7.0"
pyarrow = "^17.0.0"
pyarrow-hotfix = "^0.6"
pyasn1 = "^0.6.0"
pyasn1-modules = "^0.4.0"
pycparser = "^2.22"
pygments = "^2.18.0"
pyparsing = "^3.1.4"
pyproject-hooks = "^1.1.0"
pysocks = "^1.7.1"
python-dateutil = "^2.9.0.post0"
pytz = "^2024.1"
pyyaml = "^6.0.2"
rapidfuzz = "^3.9.6"
regex = "^2024.7.24"
requests = "^2.32.3"
requests-toolbelt = "^1.0.0"
responses = "^0.25.3"
rich = "^13.8.0"
rsa = "^4.9"
safetensors = "^0.4.4"
seaborn = "^0.13.2"
secretstorage = "^3.3.3"
sentry-sdk = "^2.13.0"
setproctitle = "^1.3.3"
setuptools = "^74.0.0"
shellingham = "^1.5.4"
shtab = "^1.7.1"
six = "^1.16.0"
smmap = "^5.0.1"
sympy = "^1.13.2"
tbb = "^2021.13.1"
threadpoolctl = "^3.5.0"
tokenizers = "^0.20.0"
tomlkit = "^0.13.2"
tqdm = "^4.66.5"
trove-classifiers = "^2024.7.2"
typing-extensions = "^4.12.2"
tyro = "^0.8.10"
tzdata = "^2024.1"
unzip = "^1.0.0"
uritemplate = "^4.1.1"
urllib3 = "^2.2.2"
virtualenv = "^20.26.3"
wandb = "^0.17.8"
wheel = "^0.44.0"
xxhash = "^3.5.0"
yarl = "^1.9.7"
zipp = "^3.20.1"
zstd = "^1.5.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
